version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  cost-simulator:
    image: python:3.9-slim
    container_name: cost-simulator
    working_dir: /app
    volumes:
      - ../scripts:/app:ro
    command: >
      sh -c "pip install prometheus_client &&
             python cost-simulator.py"
    # expose port only to the network (not host)
    ports:
    - "8000:8000"
    depends_on:
      - prometheus

volumes:
  grafana-storage:
