name: CloudLens Cleanup

on:
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Prometheus
        run: |
          docker run -d --name prometheus \
            -p 9090:9090 \
            -v ${{ github.workspace }}/docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml:ro \
            prom/prometheus:latest

      - name: Start Cost Simulator
        run: |
          docker run -d --name cost-simulator \
            -p 8000:8000 \
            -v ${{ github.workspace }}/scripts:/app:ro \
            python:3.9-slim \
            sh -c "pip install prometheus_client && python /app/cost-simulator.py"

      - name: Wait for services to warm up
        run: sleep 15

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run cleanup-detector
        run: |
          pip install requests
          python scripts/cleanup-detector.py http://localhost:9090 20 8 > cleanup-report.txt

      - name: Create issue on anomalies
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: '🚨 CloudLens Cleanup Anomalies'
          content-filepath: cleanup-report.txt
          token: ${{ secrets.GITHUB_TOKEN }}
